Repository eclipse-zenoh/zenoh-kotlin, pull requests merged in 2024-12, with the labels that each got.

#306 chore: update workflow name
  .github/workflows/publish-android.yml
Labels: internal

#326 fix: exclude internal from automatic changelog
  .github/release.yml
Labels: internal

#325 Add CI for checking markdown format.
  .github/workflows/ci.yml
  .markdownlint.yaml
  README.md
  examples/README.md
Labels: internal

#328 Springboot native lib loading: fallback to javaClass classloader
  zenoh-kotlin/src/jvmMain/kotlin/io/zenoh/Zenoh.kt
Labels: bug, enhancement, release

#324 Fix flaky Liveliness test
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/LivelinessTest.kt
Labels: bug, internal
