Repository eclipse-zenoh/zenoh-kotlin, pull requests merged in 2024-11, with the labels that each got.

#286 Maven publication: adding Maven central repository
  .github/workflows/publish-android.yml
  .github/workflows/publish-jvm.yml
  zenoh-kotlin/build.gradle.kts
Labels: release, internal

#293 fix: Don't tag release branch during dry-run
  .github/workflows/release.yml
  ci/scripts/bump-and-tag.bash
Labels: internal

#298 fix: inherit secrets to pass to reusable workflow
  .github/workflows/release.yml
Labels: internal

#299 fix: inherit secret and add debug for workflows
  .github/workflows/ci.yml
  .github/workflows/publish-android.yml
  .github/workflows/publish-jvm.yml
  .github/workflows/release.yml
  zenoh-kotlin/build.gradle.kts
Labels: internal

#300 fix: use gpg subkey id to sign maven artifacts
  .github/workflows/publish-android.yml
  .github/workflows/publish-jvm.yml
  zenoh-kotlin/build.gradle.kts
Labels: internal

#294 Android logging: pstore logs disabled
  zenoh-jni/src/logger.rs
Labels: bug, release

#295 Scouting: closing channel when scout is closed.
  zenoh-jni/src/scouting.rs
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Zenoh.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIScout.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/ScoutTest.kt
Labels: bug, release

#301 fix: remove debug from gradle
  .github/workflows/publish-android.yml
  .github/workflows/publish-jvm.yml
  .github/workflows/release.yml
Labels: internal

#305 fix: update groupdId for maven publication
  README.md
  zenoh-kotlin/build.gradle.kts
Labels: internal
