Repository eclipse-zenoh/zenoh-kotlin, pull requests merged in 2024-10, with the labels that each got.

#246 Api sync
  examples/src/main/kotlin/io.zenoh/ZBytes.kt
  zenoh-jni/Cargo.lock
  zenoh-jni/Cargo.toml
  zenoh-jni/src/lib.rs
  zenoh-jni/src/utils.rs
  zenoh-jni/src/zbytes.rs
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/bytes/ZBytes.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/ext/ZDeserialize.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/ext/ZSerialize.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/UserAttachmentTest.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/ZBytesTest.kt
Labels: release, internal

#248 Docs revision
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/bytes/Encoding.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/config/Config.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/handlers/Handler.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/publication/Publisher.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/query/Queryable.kt
Labels: documentation, release, internal

#258 Revert "Native lib loading refactor"
  zenoh-kotlin/src/jvmMain/kotlin/io/zenoh/Zenoh.kt
Labels: bug, release, internal

#260 Replace `with` with `callback` calls after Zenoh update
  zenoh-jni/Cargo.lock
  zenoh-jni/src/session.rs
Labels: release, internal

#262 fix: align Encoding API
  zenoh-jni/Cargo.lock
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/bytes/Encoding.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/EncodingTest.kt
Labels: internal

#265 Fix SessionInfoTest failing on Ubuntu
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/SessionInfoTest.kt
Labels: bug, release, internal

#273 Zbytes docs
  examples/src/main/kotlin/io.zenoh/ZBytes.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/bytes/ZBytes.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/ext/ZDeserialize.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/ext/ZSerialize.kt
Labels: documentation, release, internal

#272 Readme update
  README.md
Labels: documentation, release, internal

#281 Refactoring JVM target determination + adding arm64 support for windows
  .github/workflows/publish-jvm.yml
  zenoh-kotlin/src/jvmMain/kotlin/io/zenoh/Target.kt
  zenoh-kotlin/src/jvmMain/kotlin/io/zenoh/Zenoh.kt
Labels: bug, enhancement, release

#280 Documentation fixes + improvements
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/ZenohType.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/bytes/IntoZBytes.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/handlers/Handler.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIPublisher.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIQueryable.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISubscriber.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/keyexpr/KeyExpr.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/pubsub/Publisher.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/pubsub/Subscriber.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/qos/Reliability.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/query/Query.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/query/Queryable.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/session/SessionDeclaration.kt
Labels: documentation, release

#283 Selector: Adding missing static 'tryFrom' method
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/query/IntoSelector.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/query/Selector.kt
Labels: enhancement, release
