Repository eclipse-zenoh/zenoh-kotlin, pull requests merged in 2024-09, with the labels that each got.

#186 Use default ConsolidationMode in Session.get
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt
Labels: internal

#188 Api alignment: Config alignment
  examples/src/main/kotlin/io.zenoh/Config.kt
  zenoh-jni/src/config.rs
  zenoh-jni/src/lib.rs
  zenoh-jni/src/scouting.rs
  zenoh-jni/src/session.rs
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Config.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIConfig.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIScout.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIZBytes.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/ConfigTest.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/SessionTest.kt
Labels: enhancement, release

#191 Update readme after 1.0.0-beta.1 release.
  README.md
Labels: documentation

#192 Replacing ZBytes params for IntoZBytes.
  examples/src/main/kotlin/io.zenoh/ZBytes.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIPublisher.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIQuery.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/protocol/Deserializable.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/protocol/IntoZBytes.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/protocol/ZBytes.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/publication/Publisher.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/queryable/Query.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/ZBytesTest.kt
Labels: enhancement, internal

#193 fix(examples): load config error
  examples/src/main/kotlin/io.zenoh/Config.kt
Labels: bug, internal

#201 feat(deserialization): removing Deserializable interface
  examples/src/main/kotlin/io.zenoh/ZBytes.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/protocol/Deserializable.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/protocol/ZBytes.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/ZBytesTest.kt
Labels: release, internal

#203 Fixes after cargo update
  zenoh-jni/Cargo.lock
  zenoh-jni/src/publisher.rs
  zenoh-jni/src/query.rs
  zenoh-jni/src/session.rs
Labels: release, internal

#205 fix(scout): error when closing scout + API rework
  zenoh-jni/src/scouting.rs
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Zenoh.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIScout.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/scouting/Scout.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/ScoutTest.kt
Labels: bug

#199 Moving reliability config param from subscriber to the publisher, and to session put and delete
  examples/src/main/kotlin/io.zenoh/ZSubThr.kt
  zenoh-jni/src/session.rs
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/publication/Delete.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/publication/Put.kt
Labels: enhancement, release

#208 api(selector): alignment of the selector api
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/selector/IntoSelector.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/selector/Parameters.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/selector/Selector.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/GetTest.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/ParametersTest.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/SelectorTest.kt
Labels: enhancement, release

#210 chore: update zenoh version
  zenoh-jni/Cargo.lock
  zenoh-jni/src/queryable.rs
  zenoh-jni/src/session.rs
Labels: internal

#214 Fix scout example
  examples/src/main/kotlin/io.zenoh/ZScout.kt
Labels: bug

#212 Restricting visibility for attributes and internal functions
  examples/src/main/kotlin/io.zenoh/ZPubThr.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIScout.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIZBytes.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/prelude/CongestionControl.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/prelude/Priority.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/prelude/SampleKind.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/query/ConsolidationMode.kt
Labels: release, internal

#213 Alignment: Adding `tryInitLogFromEnv`
  zenoh-kotlin/src/androidMain/kotlin/io.zenoh/Zenoh.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Zenoh.kt
  zenoh-kotlin/src/jvmMain/kotlin/io/zenoh/Zenoh.kt
Labels: release, internal

#218 Making Session.open(config) internal, exposing it through Zenoh.open(…
  examples/src/main/kotlin/io.zenoh/ZDelete.kt
  examples/src/main/kotlin/io.zenoh/ZGet.kt
  examples/src/main/kotlin/io.zenoh/ZPub.kt
  examples/src/main/kotlin/io.zenoh/ZPubThr.kt
  examples/src/main/kotlin/io.zenoh/ZPut.kt
  examples/src/main/kotlin/io.zenoh/ZQueryable.kt
  examples/src/main/kotlin/io.zenoh/ZSub.kt
  examples/src/main/kotlin/io.zenoh/ZSubThr.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Zenoh.kt
Labels: enhancement, release

#220 Improve tryInitLogFromEnv logic
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Zenoh.kt
Labels: release, internal

#225 Point Cargo manifest to `internal-config` branch
  zenoh-jni/src/session.rs
  zenoh-jni/src/zenoh_id.rs
Labels: bug, internal

#227 Config alignment
  zenoh-jni/src/config.rs
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Config.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIConfig.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/ConfigTest.kt
Labels: enhancement, release

#235 Align Rust with Reliability exported in zenoh::qos
  zenoh-jni/Cargo.lock
  zenoh-jni/src/utils.rs
Labels: internal

#223 fix(scouting): error when providing config
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIScout.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/ScoutTest.kt
Labels: release, internal

#230 Session info
  examples/build.gradle.kts
  examples/src/main/kotlin/io.zenoh/ZInfo.kt
  zenoh-jni/src/session.rs
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/SessionInfo.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/SessionInfoTest.kt
Labels: enhancement, release

#231 Zerror
  zenoh-jni/src/config.rs
  zenoh-jni/src/errors.rs
  zenoh-jni/src/key_expr.rs
  zenoh-jni/src/logger.rs
  zenoh-jni/src/publisher.rs
  zenoh-jni/src/query.rs
  zenoh-jni/src/scouting.rs
  zenoh-jni/src/session.rs
  zenoh-jni/src/utils.rs
  zenoh-jni/src/zbytes.rs
  zenoh-jni/src/zenoh_id.rs
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Logger.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/exceptions/KeyExprException.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/exceptions/SessionException.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/exceptions/ZError.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIConfig.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIKeyExpr.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIPublisher.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIQuery.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIScout.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/keyexpr/IntoKeyExpr.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/protocol/ZBytes.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/publication/Publisher.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/queryable/Query.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/selector/IntoSelector.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/ConfigTest.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/KeyExprTest.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/SelectorTest.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/SessionTest.kt
Labels: release, internal

#236 Publisher alignment
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/keyexpr/SetIntersectionLevel.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/publication/Publisher.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/PublisherTest.kt
Labels: release, internal

#233 Renaming ZenohID to ZenohId
  zenoh-jni/src/zenoh_id.rs
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Config.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/SessionInfo.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIScout.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIZenohId.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/protocol/ZenohId.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/query/Reply.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/scouting/Hello.kt
Labels: release, internal

#238 alignment(session): replacing `isOpen` with `isClosed`.
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/SessionTest.kt
Labels: release, internal

#240 Making 'Target' internal
  zenoh-kotlin/src/jvmMain/kotlin/io/zenoh/Target.kt
Labels: release, internal

#239 Packages reordering
  examples/src/main/kotlin/io.zenoh/Config.kt
  examples/src/main/kotlin/io.zenoh/ZBytes.kt
  examples/src/main/kotlin/io.zenoh/ZGet.kt
  examples/src/main/kotlin/io.zenoh/ZPub.kt
  examples/src/main/kotlin/io.zenoh/ZPubThr.kt
  examples/src/main/kotlin/io.zenoh/ZPut.kt
  examples/src/main/kotlin/io.zenoh/ZQueryable.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Zenoh.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/bytes/Encoding.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/bytes/IntoZBytes.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/bytes/ZBytes.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/config/Config.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/config/ZenohId.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIConfig.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIPublisher.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIQuery.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIScout.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIZBytes.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/keyexpr/KeyExpr.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/publication/Delete.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/publication/Publisher.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/publication/Put.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/qos/CongestionControl.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/qos/Priority.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/qos/QoS.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/qos/Reliability.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/query/Query.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/query/Queryable.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/query/Reply.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/query/ReplyError.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/sample/Sample.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/sample/SampleKind.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/scouting/Hello.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/session/SessionDeclaration.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/session/SessionInfo.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/subscriber/Subscriber.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/ConfigTest.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/DeleteTest.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/EncodingTest.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/GetTest.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/KeyExprTest.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/PublisherTest.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/PutTest.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/QueryableTest.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/ScoutTest.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/SessionInfoTest.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/SessionTest.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/SubscriberTest.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/UserAttachmentTest.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/ZBytesTest.kt
Labels: release, internal

#242 Align with Rust
  zenoh-jni/Cargo.lock
  zenoh-jni/src/query.rs
  zenoh-jni/src/scouting.rs
  zenoh-jni/src/session.rs
Labels: internal

#245 chore: update release.yml for required labels
  .github/release.yml
Labels: internal
