Repository eclipse-zenoh/zenoh-kotlin, pull requests merged in 2025-01, with the labels that each got.

#331 Nexus publish
  .github/workflows/publish-android.yml
  .github/workflows/publish-jvm.yml
  build.gradle.kts
  zenoh-kotlin/build.gradle.kts
Labels: release, internal

#333 Fix selector "null" parameter
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/SelectorTest.kt
Labels: bug, release

#340 CI workflow: fix relative cargo.toml path after gradle upgrade to 8.12
  build.gradle.kts
  examples/build.gradle.kts
  zenoh-kotlin/build.gradle.kts
Labels: bug, internal

#338 Providing function overloads that receive String params instead of ZBytes
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/pubsub/Publisher.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/query/Querier.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/query/Query.kt
Labels: enhancement, release

#334 Examples refactor
  examples/src/main/kotlin/io.zenoh/ZDelete.kt
  examples/src/main/kotlin/io.zenoh/ZGet.kt
  examples/src/main/kotlin/io.zenoh/ZGetLiveliness.kt
  examples/src/main/kotlin/io.zenoh/ZInfo.kt
  examples/src/main/kotlin/io.zenoh/ZLiveliness.kt
  examples/src/main/kotlin/io.zenoh/ZPong.kt
  examples/src/main/kotlin/io.zenoh/ZPub.kt
  examples/src/main/kotlin/io.zenoh/ZPubThr.kt
  examples/src/main/kotlin/io.zenoh/ZPut.kt
  examples/src/main/kotlin/io.zenoh/ZQuerier.kt
  examples/src/main/kotlin/io.zenoh/ZQueryable.kt
  examples/src/main/kotlin/io.zenoh/ZScout.kt
  examples/src/main/kotlin/io.zenoh/ZSub.kt
  examples/src/main/kotlin/io.zenoh/ZSubLiveliness.kt
Labels: release, internal

#344 Fix publications inputs processing
  .github/workflows/publish-android.yml
  .github/workflows/publish-jvm.yml
Labels: release, internal

#346 Expliciting group, version and sonatype urls + problem reports
  .github/workflows/publish-android.yml
  .github/workflows/publish-jvm.yml
  build.gradle.kts
Labels: release, internal

#350 Maven publication: modifying nexus url
  build.gradle.kts
Labels: bug, internal

#348 fix: always upload problem report
  .github/workflows/publish-android.yml
  .github/workflows/publish-jvm.yml
Labels: internal

#351 Maven publication: fix 'unspecified' version
  zenoh-kotlin/build.gradle.kts
Labels: bug, internal

#352 Maven publication: fix snapshot versioning
  build.gradle.kts
  zenoh-kotlin/build.gradle.kts
Labels: bug, internal

#353 Maven publication: splitting publication step on workflows
  .github/workflows/publish-android.yml
  .github/workflows/publish-jvm.yml
Labels: bug, internal

#354 Fix artifact upload
  .github/workflows/publish-android.yml
  .github/workflows/publish-jvm.yml
Labels: internal

#356 fix: publish to github and dokka after maven
  .github/workflows/release.yml
Labels: internal

#357 fix: release staging repository with publication
  .github/workflows/publish-android.yml
  .github/workflows/publish-jvm.yml
Labels: internal

#359 fix: add output to GITHUB_ENV
  .github/workflows/publish-android.yml
  .github/workflows/publish-jvm.yml
Labels: internal

#360 fix: run gradlew with --info
  .github/workflows/publish-android.yml
  .github/workflows/publish-jvm.yml
Labels: internal

#362 Examples fat JARs
  build.gradle.kts
  examples/README.md
  examples/build.gradle.kts
Labels: enhancement, internal

#364 Maven publication: adding javadoc jar to maven publication
  .github/workflows/publish-jvm.yml
  zenoh-kotlin/build.gradle.kts
Labels: release, internal

#366 Upgrade Dokka to 2.0.0
  .github/workflows/publish-dokka.yml
  .github/workflows/publish-jvm.yml
  .gitignore
  build.gradle.kts
  gradle.properties
  zenoh-kotlin/build.gradle.kts
Labels: bug, documentation, release, internal

#371 Fix cargo relative path after gradle 8.12.1
  .github/workflows/ci.yml
  examples/build.gradle.kts
  zenoh-kotlin/build.gradle.kts
Labels: bug, internal

#375 chore: update Cargo.toml to main zenoh branch
  .github/workflows/ci.yml
  .github/workflows/publish-android.yml
  .github/workflows/publish-jvm.yml
  .github/workflows/release.yml
  zenoh-jni/Cargo.lock
  zenoh-jni/Cargo.toml
Labels: internal

#369 Removing workflow_dispatch from android and jvm publication workflows
  .github/workflows/publish-android.yml
  .github/workflows/publish-jvm.yml
Labels: bug, internal

#376 fix: use dokkaGenerate to avoid doc build failure
  .github/workflows/publish-dokka.yml
Labels: internal
