Repository eclipse-zenoh/zenoh-kotlin, pull requests merged in 2025-02, with the labels that each got.

#379 Update git branch
  zenoh-jni/Cargo.lock
  zenoh-jni/Cargo.toml
Labels: internal

#389 Adding missing QoS param to Get operations.
  zenoh-jni/src/session.rs
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt
Labels: bug, release

#390 Adopt the different congestion control defaults as in Rust
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/qos/QoS.kt
  zenoh-kotlin/src/commonMain/kotlin/io/zenoh/query/Query.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/QuerierTest.kt
  zenoh-kotlin/src/commonTest/kotlin/io/zenoh/QueryableTest.kt
Labels: enhancement, release
